infinitest/infinitest

infinitest-eclipse/src/main/java/org/infinitest/eclipse/resolution/ErrorViewerResolution.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/resolution/FailureViewer.java
This pull request Fixes the issue #163
=> Fix issue#163: Quick fix Dialog is now opened on the monitor where the

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/IdeaModuleSettings.java
fix list of output directories in case one is null.
add output directories from dependant modules.  This allows more thorough analysis of test impact as well as providing a proper way of dealing with module groups with inter dependencies.
=> intellij 2016

infinitest-eclipse/src/main/java/org/infinitest/eclipse/prefs/PreferencePage.java
=> 116: Use Infinitest Core constant limit in Preference Page

.travis.yml, README.md, codecov.yml, pom.xml
=> Setup codecov

infinitest-lib/.gitignore, infinitest-lib/pom.xml, infinitest-lib/src/main/java/org/infinitest/InfinitestCoreBuilder.java, infinitest-lib/src/test/java/org/infinitest/TestFilterList.java, infinitest-lib/src/test/java/org/infinitest/WhenStrictlyComparingTestEvents.java, infinitest-lib/src/test/java/org/infinitest/WhenTheFilterFileChanges.java, infinitest-lib/src/test/java/org/infinitest/filter/RegexFileFilterTest.java, infinitest-runner/.gitignore, infinitest-runner/pom.xml, infinitest-runner/src/main/java/org/infinitest/TestNGConfigurator.java, infinitest-runner/src/main/java/org/infinitest/config/FileBasedInfinitestConfigurationSource.java, infinitest-runner/src/main/java/org/infinitest/config/InfinitestConfiguration.java, infinitest-runner/src/main/java/org/infinitest/config/InfinitestConfigurationParser.java, infinitest-runner/src/main/java/org/infinitest/config/InfinitestConfigurationSource.java, infinitest-runner/src/main/java/org/infinitest/config/MemoryInfinitestConfigurationSource.java, infinitest-runner/src/test/java/org/infinitest/TestNGConfiguratorTest.java, infinitest-runner/src/test/java/org/infinitest/config/InfinitestConfigurationParserTest.java, pom.xml
This pull request resolves #211
=> Review infinitest filters format

infinitest-runner/src/main/java/org/infinitest/testrunner/TestEvent.java, infinitest-runner/src/test/java/org/infinitest/testrunner/JUnit4RunnerTest.java, infinitest-runner/src/test/java/org/infinitest/testrunner/TestEventTest.java, infinitest-runner/src/test/java/org/infinitest/testrunner/exampletests/junit4/Junit4TestThatThrowsExceptionWithNullStack.java
=> fix(TestEvent): handle exception with null stack traces

infinitest-lib/src/main/java/org/infinitest/parser/ClassFileIndex.java
findClass() does a linear search on the graph vertices, this takes very long on large projects.
Keep track of the classes in a Map instead
=> perf: remove linear search in ClassFileIndex

infinitest-intellij/pom.xml, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/language/InfinitestHighlightingPassFactory.java
- the bintray repository no longer works, changed to jetbrains' repos
- updated to intellij 20.1.0
- modified InfinitestHighlightingPassFactory to conform to the updated intellij API
=> deps: updated intellij dependencies

infinitest-lib/src/test/java/org/infinitest/WhenTheFilterFileChanges.java
WhenTheFilterFileChanges creates a file but never deletes
=> test: fixed file leak in Infinitest own unit test

.github/workflows/release.yml, CONTRIBUTING.md, infinitest-eclipse/pom.xml, infinitest-eclipse/src/main/assembly/assembly-site-zip.xml, pom.xml
- Added a workflow running the build when a release is published
- Upload the plugins into the release page
fixes #207
fixes #249
=> ci: build and sign the plugins when releasing a new version

CONTRIBUTING.md, infinitest-intellij/src/main/resources/META-INF/plugin.xml
- Description too short
- Only compatible with IntelliJ 2018-3 and above
- Missing dependency (need at least one)
=> fix: adjustments for the new requirements of the IntelliJ marketplace

infinitest-eclipse-feature/pom.xml, infinitest-eclipse/pom.xml
The group id is `org.infinitest.eclipse` for the feature
=> fix: incorrect plugin id in feature.xml

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/facet/InfinitestFacetConfiguration.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/launcher/InfinitestBuilder.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/launcher/InfinitestLauncherImpl.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/launcher/InfinitestPresenter.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/swingui/InfinitestConsoleFrame.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/swingui/InfinitestMainFrame.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/swingui/InfinitestView.java, infinitest-intellij/src/test/java/org/infinitest/intellij/WhenLaunchingInfinitest.java, infinitest-intellij/src/test/java/org/infinitest/intellij/plugin/swingui/TestInfinitestMainFrame.java, infinitest-intellij/src/test/java/org/infinitest/intellij/plugin/swingui/WhenShowingMainFrame.java
Added a console view to help with the debugging
=> feature: added a console to the IntelliJ plugin

infinitest-runner/src/test/java/org/infinitest/testrunner/TestEventTest.java, pom.xml
Not sure how to reproduce, but apparently fixes #269
=> deps: upgrade AssertJ to 3.11.1

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/ProjectTestControl.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/launcher/InfinitestPresenter.java, infinitest-intellij/src/test/java/org/infinitest/TestInfinitestPresenter.java, infinitest-intellij/src/test/java/org/infinitest/intellij/IntellijMockBase.java, infinitest-intellij/src/test/java/org/infinitest/intellij/idea/IdeaTestControlTest.java, infinitest-intellij/src/test/java/org/infinitest/intellij/plugin/swingui/WhenDisplayingResultsInATree.java
Disable Infinitest when the power save mode is enable, this fixes #139
=> feature: disable infinitest with power save mode

infinitest-eclipse/src/main/java/org/infinitest/eclipse/EclipsePluginInfinitestJarsLocator.java, infinitest-lib/src/main/java/org/infinitest/environment/RuntimeEnvironment.java, infinitest-lib/src/main/java/org/infinitest/util/InfinitestUtils.java
Prevent other users from reading, writing or executing the temporary files create by Infinitest
=> fix: create temp files securely

infinitest-eclipse/src/main/java/org/infinitest/eclipse/resolution/StackElementSelectionListener.java, infinitest-intellij/src/main/java/org/infinitest/intellij/InfinitestLoggingListener.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/IdeaLogService.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/LogService.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/LogServiceState.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/window/InfinitestToolWindowFactory.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/swingui/InfinitestLogPane.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/swingui/InfinitestMainFrame.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/swingui/InfinitestView.java, infinitest-intellij/src/test/java/org/infinitest/intellij/FakeInfinitestView.java, infinitest-intellij/src/test/java/org/infinitest/intellij/IntellijMockBase.java, infinitest-intellij/src/test/java/org/infinitest/intellij/WhenLoggingError.java, infinitest-intellij/src/test/java/org/infinitest/intellij/WhenLoggingMessage.java, infinitest-intellij/src/test/java/org/infinitest/intellij/idea/IdeaLogServiceTest.java, infinitest-intellij/src/test/java/org/infinitest/intellij/plugin/swingui/InfinitestLogPaneTest.java, infinitest-intellij/src/test/java/org/infinitest/intellij/plugin/swingui/TestInfinitestMainFrame.java, infinitest-intellij/src/test/java/org/infinitest/intellij/plugin/swingui/WhenShowingMainFrame.java, infinitest-intellij/src/test/java/org/infinitest/intellij/plugin/swingui/harness/LogPaneHarness.java, infinitest-lib/src/main/java/org/infinitest/testrunner/process/NativeConnectionFactory.java, infinitest-lib/src/main/java/org/infinitest/util/Events.java, infinitest-runner/src/main/java/org/infinitest/testrunner/TestRunnerProcess.java
Added an option to adjust the log level in the Infinitest "logging" tab
=> IntelliJ plugin logging improvements

.github/workflows/build.yml, .github/workflows/release.yml, infinitest-intellij/src/test/java/org/infinitest/intellij/WhenCompilationCompletes.java
xvfb-run should be installed by default on ubuntu-latest
=> build: replace xvf-action

infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/swingui/InfinitestLogPane.java
=> fix: make the intellij log view read only

infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/swingui/TreeModelAdapter.java
=> feature: sort module by alphabetical order

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/window/InfinitestToolWindowFactory.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/swingui/TreeModelAdapter.java, infinitest-intellij/src/test/java/org/infinitest/intellij/plugin/swingui/WhenDisplayingResultsInATree.java
=> feature: only display modules with test sources

infinitest-eclipse/src/main/java/org/infinitest/eclipse/markers/GenericMarkerRegistry.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/markers/ProblemMarkerRegistry.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/markers/SlowMarkerRegistry.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/markers/WhenCreatingMarkers.java
=> fix: set the default severity to info for slow tests

.github/workflows/build.yml, pom.xml
Apparently the project was deleted from sonarcloud, also it needs to run on JDK 17
=> Updated Sonar analysis

infinitest-eclipse/pom.xml
Hold on upgrading to retain Java 8/11 compatibility
=> Upgrade Spring to 5.3.39

infinitest-lib/src/main/java/org/infinitest/parser/ClassFileIndex.java, infinitest-lib/src/main/java/org/infinitest/parser/ClassFileTestDetector.java, infinitest-lib/src/main/java/org/infinitest/parser/JavaAssistClass.java, infinitest-lib/src/main/java/org/infinitest/parser/JavaClass.java, infinitest-lib/src/test/java/org/infinitest/parser/JavaAssistClassTest.java, infinitest-lib/src/test/java/org/infinitest/parser/NonPublicArchUnitTest.java, infinitest-lib/src/test/java/org/infinitest/plugin/WhenRunningTests.java
=> Run ArchUnit tests whenever there's a class change
