infinitest/infinitest

infinitest-eclipse/src/main/java/org/infinitest/eclipse/markers/ProblemMarkerInfo.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/markers/WhenCreatingMarkers.java
Fix for [Issue #174](https://github.com/infinitest/infinitest/issues/174).
=> Issue #174: Eclipse problem markers now remove new lines from error messages

infinitest-intellij/src/test/java/org/infinitest/intellij/plugin/launcher/WhenTestRunCompleted.java
Fixes a minor TODO by reenabling 2 tests that were expecting to mock object under test.
=> Use mockito spy to allow partial mocking of object under test.

infinitest-eclipse/src/main/java/org/infinitest/eclipse/resolution/ErrorViewerResolution.java
The issue was caused by main workbench shell being reactivated when
QuickFixDialog is closed.
The reactivation of the main shell deactivated the FailureViewer shell
triggering the attached DialogDeactivationDisposer which in turned
closed the FailureViewer.
Using asyncExec allows to open the FailerViewer after main shell have
been reactivated
=> Fixing issue #152 (Stack trace window opens and closes right after).

infinitest-eclipse/src/main/assembly/assembly-feature.xml, infinitest-eclipse/src/main/assembly/assembly-plugin.xml
Fixed resource filtering during assembly of the feature JAR by using ``<files>`` and ``<file>`` as suggested by the [assembly plug-in documentation](https://maven.apache.org/plugins/maven-assembly-plugin/examples/single/filtering-some-distribution-files.html).
See also infinitest/infinitest#180.
=> Fix Resource Filtering

infinitest-lib/src/main/java/org/infinitest/parser/JavaAssistClassParser.java
The issue is caused by ClassFileTestDetector filtering out any test files containing spaces. In the test file names spaces are escaped with '%20' but in the list of the project's class directories spaces are unescaped. Because of that inCurrentProject() always returns false.
The issue is fixed by creating the test class File objects from an URI. That will decode any URL encoded spaces in the file name.
=> Issue #187: No tests executed if path contains space

infinitest-lib/src/main/java/org/infinitest/filter/RegexFileFilter.java, infinitest-lib/src/test/java/org/infinitest/TestFilterList.java, infinitest-lib/src/test/java/org/infinitest/filter/RegexFileFilterTest.java
A line with the content “!whitelist” can be added to the filter list in order to invert the filters. Only tests matching any of the given filter patterns will be run.
=> Enabling whitelist-filtering

infinitest-runner/pom.xml, infinitest-runner/src/main/java/org/infinitest/testrunner/JUnit4Runner.java, infinitest-runner/src/main/java/org/infinitest/testrunner/JUnitEventTranslator.java, infinitest-runner/src/test/java/org/infinitest/TestNGConfiguratorTest.java, infinitest-runner/src/test/java/org/infinitest/testrunner/FailingTestsWithCategories.java, infinitest-runner/src/test/java/org/infinitest/testrunner/WhenConvertingJUnitEventsToInfinitestEvents.java, infinitest-runner/src/test/java/org/infinitest/testrunner/WhenRunningJUnitTests.java, infinitest-runner/src/test/java/org/infinitest/testrunner/WhenRunningTestNGTests.java
Solves issue #92. 
Specifying a JUnit category in the 'excludeGroups' entry of infinitest.filters will cause infinitest to ignore any test annotated with `@Category(TheCategoryToIgnore.class)`.
Replaces pull request #160 which was based on code too old to be worth updating.  Yeah, sorry it took me  2 years, 6 months, and 10 days to complete. :|
=> 92 junit categories 2

codecov.yml, infinitest-eclipse/src/main/java/org/infinitest/eclipse/resolution/ErrorViewerResolution.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/resolution/FailureViewer.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/resolution/FailureViewerTest.java
=> fix: Fix position of QuickFix failure viewer dialog

infinitest-eclipse/src/main/java/org/infinitest/eclipse/workspace/EclipseWorkspace.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/workspace/WorkspaceStatusFactory.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/WhenUpdatingTheProjectsInTheWorkspace.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/WorkspaceStatusFactoryTest.java
=> feat: improve status message while searching for tests

infinitest-lib/src/main/java/org/infinitest/environment/FileCustomJvmArgumentReader.java, infinitest-lib/src/test/java/org/infinitest/environment/FileCustomJvmArgumentReaderTest.java
=> fix(infinitest.args): Support space in quotes + support SplitOn config

infinitest-eclipse/pom.xml
Spring 4.3.9 bundles CGLIB, it no longer works with JDK 17 since  JEP 403. 
Upgrade to the latest version
fixes #287
=> deps: upgraded Spring

infinitest-eclipse/src/main/java/org/infinitest/eclipse/workspace/ProjectFacade.java
Java versions >= 10 clash with the test that the first letter is '1'.
Instead test if the version starts with "1."  and show the version in the error message in case the parsing failed
=> fix: handle java versions >= 10

.travis.yml, infinitest-intellij/src/main/java/org/infinitest/intellij/InfinitestJarsLocator.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/facet/InfinitestFacet.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/facet/InfinitestFacetConfiguration.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/facet/InfinitestFacetType.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/language/InfinitestHighlightingPassFactory.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/window/InfinitestToolWindow.java, infinitest-intellij/src/test/java/org/infinitest/intellij/idea/WhenBuildingIdeaModuleClassPath.java, infinitest-runner/pom.xml, infinitest-runner/src/test/java/org/infinitest/testrunner/TestEventTest.java, pom.xml
This PR builds on the unmerged #271 and adds compatibility with Java 18
=> java18 compatibility

.github/workflows/build.yml
- Run the build using multiple versions of Java
- Cache the maven dependencies
- Install GTK2 for SWT unit tests
- Install Xvfb for Swing unit tests
=> ci: added a build running the unit tests

infinitest-intellij/src/main/resources/META-INF/plugin.xml
Intellij is trying to find a class on the classpath with the line break, which causes a class not found exception.
So, I just removed the line breaks.
=> 285 - format xml to avoid class loading issue by intellij

infinitest-runner/src/main/java/org/infinitest/testrunner/junit4/Junit4And3Runner.java, testWorkspace/mavenproject/pom.xml
Guard the category filter with a check. If no excludes are defined, just
skip the whole category filter, otherwise, if there's an error creating
the filter then throw an exception since that only happens in Junit
<4.12
This fixes #265
=> Handle CatgegoryFilter being different in 4.12

infinitest-intellij/pom.xml, infinitest-intellij/src/main/java/org/infinitest/intellij/ModuleSettings.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/IdeaModuleSettings.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/launcher/InfinitestLauncherImpl.java, infinitest-intellij/src/main/resources/META-INF/maven/org.infinitest/infinitest-intellij/pom.xml, infinitest-intellij/src/test/java/org/infinitest/intellij/FakeModuleSettings.java
- picocontainer seems unused
- log4j 1.2 is unmaintained and has vulnerabilities, replace it with IntelliJ's built-in logger
- sanselan is unmaintained and has vulnerabilities, it seems unused
=> deps: removed obsolete dependencies

infinitest-lib/pom.xml, infinitest-lib/src/main/java/org/infinitest/parser/JavaAssistClass.java, infinitest-lib/src/test/java/com/fakeco/fakeproduct/JUnit5CompositeAnnotation.java, infinitest-lib/src/test/java/com/fakeco/fakeproduct/JUnit5CompositeAnnotationTest.java, infinitest-lib/src/test/java/com/fakeco/fakeproduct/JUnit5ParameterizedTest.java, infinitest-lib/src/test/java/org/infinitest/parser/JavaAssistClassTest.java, infinitest-runner/src/test/java/org/infinitest/testrunner/JUnit5RunnerTest.java, infinitest-runner/src/test/java/org/infinitest/testrunner/exampletests/junit5/FastTestCombinedAnnotation.java, infinitest-runner/src/test/java/org/infinitest/testrunner/exampletests/junit5/JUnit5TestUsingComposedAnnotation.java
Adds support for JUnit5 combined annotation: https://junit.org/junit5/docs/current/user-guide/#writing-tests-meta-annotations
- When checking if a method is a test, look for combined annotations
- Look for annotations that are themselves annotated with `TestTemplate `to support `ParameterizedTest`
- Added sample classes covering the new cases
Fixes #276
Fixes #268
=> feature: support for JUnit 5 combined annotations

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/language/InfinitestHighlightingPassFactory.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/launcher/FileEditorListener.java
Store the pass in the editor instead of calling fileEditor.getBackgroundHighlighter().createPassesForEditor(), that method recreates the passes and must not be called from the EDT while highlightingPass.applyInformationToEditor() must be called from the EDT.
fixes #233
fixes #274
=> fix: keep track of the HighlightingPass

infinitest-runner/pom.xml, pom.xml
=> deps: align the jcommander version with the unpacked version

infinitest-classloader/pom.xml, infinitest-eclipse/pom.xml, infinitest-intellij/pom.xml, infinitest-intellij/src/main/resources/META-INF/maven/org.infinitest/infinitest-intellij/pom.xml, infinitest-lib/pom.xml, infinitest-runner/pom.xml, pom.xml
We should be good to release a new version now:
- The blocking dependencies have been upgraded
- A new GitHub action build [release.yml](https://github.com/infinitest/infinitest/blob/master/.github/workflows/release.yml) has been added to build and sign the plugins
- The [CONTRIBUTING.md](https://github.com/infinitest/infinitest/blob/master/CONTRIBUTING.md) file has been updated with the new process
- The upload of the Eclipse and IntelliJ plugins is not automated for now, so it must be done manually
It might take a couple of tries to get the workflow to build so I'll commit the new SNAPSHOT version later
Fixes #279 
Fixes #297
=> release 5.3.0

infinitest-eclipse/src/test/java/org/infinitest/eclipse/EclipsePluginInfinitestJarsLocatorTest.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/FailureMediatorTest.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/event/WhenCheckingForSaveEvents.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/event/WhenDispatchingResourceChangeEvents.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/event/WhenNoProcessorsCanHandleEvent.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/event/WhenRespondingToBuildEvents.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/event/WhenRespondingToCleanEvents.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/event/WhenRespondingToResourceChangeEvents.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/markers/FakeProblemMarkerInfo.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/markers/WhenPlacingMarkersInJavaClasses.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/prefs/WhenPreferencesAreChanged.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/trim/WhenShowingStatusInTheStatusBar.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/JavaProjectBuilder.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/WhenCompileErrorsExistInAProject.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/WhenCoresAreAddedOrRemoved.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/WhenResolvingClassPath.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/WhenUpdatingTheProjectsInTheWorkspace.java, infinitest-intellij/src/test/java/org/infinitest/TestInfinitestPresenter.java, infinitest-intellij/src/test/java/org/infinitest/intellij/WhenCompilationCompletes.java, infinitest-intellij/src/test/java/org/infinitest/intellij/WhenLaunchingInfinitest.java, infinitest-intellij/src/test/java/org/infinitest/intellij/WhenLoggingError.java, infinitest-intellij/src/test/java/org/infinitest/intellij/WhenLoggingMessage.java, infinitest-lib/src/test/java/org/infinitest/WhenATestIsRun.java, infinitest-lib/src/test/java/org/infinitest/WhenTestsAreDisabled.java, infinitest-lib/src/test/java/org/infinitest/WhenTestsResultsAreProcessed.java, infinitest-lib/src/test/java/org/infinitest/WhenTheRuntimeEnvironmentChanges.java, infinitest-lib/src/test/java/org/infinitest/WhenWatchingMultipleCores.java, infinitest-lib/src/test/java/org/infinitest/plugin/WhenRunningTests.java, infinitest-lib/src/test/java/org/infinitest/testrunner/ResultProcessorTest.java, pom.xml
Mocking abstract classes fails with mockito 1.10.8 and java >= 16 since it uses the unmaintained CGLIB
=> deps: upgrade mockito to 4.7.0

infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/WhenResolvingClassPath.java, pom.xml
- upgrade surefire to 3.0.0-M7
- surefire now reports unused mockito stubbings and fails the build, remove unused stubbings in WhenResolvingClassPath
=> deps: upgrade surefire to 3.0.0-M7

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/IdeaModuleSettings.java, infinitest-intellij/src/test/java/org/infinitest/intellij/idea/WhenBuildingIdeaModuleClassPath.java
The intellij log is cluttered by messages about modules
=> fix: jdk modules should be excluded when building the classpath

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/IdeaSourceNavigator.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/language/InfinitestLineMarkersPass.java
The test might fail to initialize in a class from a library as it was the case for #319. Search in the 'all' scope (including libraries) for the point of failure. Since we might land in a decompiled class the line number might be outside of the range for the decompiled source, so we need to adjust it or we get an exception in the highlighter pass
Fixes #253
=> fix: search the point of failure in the 'all' scope

infinitest-eclipse/src/main/java/org/infinitest/eclipse/prefs/PreferenceChangeHandler.java
Sonar's S6320 rule complains that newValue might be a Boolean, added 'else' since the ifs are mutually exclusive
=> fix: unrelated ifs confuse sonar's S6320 rule

infinitest-lib/src/main/java/org/infinitest/environment/ClasspathArgumentBuilder.java, infinitest-lib/src/main/java/org/infinitest/environment/FileClasspathArgumentBuilder.java, infinitest-lib/src/main/java/org/infinitest/environment/RuntimeEnvironment.java, infinitest-lib/src/main/java/org/infinitest/environment/SimpleClasspathArgumentBuilder.java, infinitest-lib/src/main/java/org/infinitest/testrunner/process/NativeConnectionFactory.java, infinitest-lib/src/main/java/org/infinitest/testrunner/process/NativeProcessConnection.java, infinitest-lib/src/test/java/org/infinitest/environment/RuntimeEnvironmentTest.java, infinitest-lib/src/test/java/org/infinitest/testrunner/process/WhenCreatingRunnerProcessConnection.java
mockito-inline relies on instrumentation to mock static methods, this does not seem to be possible when the classloader is overridden because it does not implement the required methods
Pull request #260 was introduced to solve the problem when the classpath is too big to fit in the shell environment.
Since Java 9 it is possible to use argument file expanded by the java process, use this native feature instead of a custom classloader 
https://docs.oracle.com/en/java/javase/15/docs/specs/man/java.html#java-command-line-argument-files
Introduced ClasspathArgumentBuilder to the pre Java 9 case (use standard arguments) and post Java 9 (use an argument file)
Fixes #319
=> fix: replacing the system classloader prevents instrumentation

infinitest-lib/pom.xml, pom.xml
3.18.2 is quite old and the new version is much faster (see #12), reduces by 80% the time it spent (~1mn) to parse the java classes on a sample largeish project
=> deps: upgrade javassist to 3.29.2

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/IdeaModuleSettings.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/InfinitestRunConfigurationParameters.java
- module.getModuleFilePath() is an internal method and shouldn't be used by plugins, according to the javadoc the path returned might not exist
- instead use ProgramParametersConfigurator with a mock/null configuration
- can't seem to be possible to use MacroManager so no unit test for this change
- fixes #344
=> fix: use the built-in utility to compute the working dir of a module

infinitest-lib/src/main/java/org/infinitest/environment/RuntimeEnvironment.java, infinitest-lib/src/test/java/org/infinitest/environment/RuntimeEnvironmentTest.java
Added double quotes in case the path contains space characters, escape backslashes
=> fix: escape the content of the classpath argument file

CONTRIBUTING.md, infinitest-intellij/pom.xml
- set the java version to 11
- exclude transitive dependency containing the org.xml.sax package
- Updated docs with JDK requirements
=> fix: explicitely set java level to 11 for the intellij module

infinitest-eclipse/src/main/java/org/infinitest/eclipse/InfinitestActivationController.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/event/ClassFileChangeProcessor.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/workspace/EclipseWorkspace.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/workspace/ProjectFacade.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/workspace/WorkspaceFacade.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/WhenActivatingThePlugin.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/event/WhenRespondingToBuildEvents.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/JavaProjectBuilder.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/WhenCompileErrorsExistInAProject.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/WhenUpdatingTheProjectsInTheWorkspace.java, infinitest-lib/src/main/java/org/infinitest/DefaultInfinitestCore.java, infinitest-lib/src/main/java/org/infinitest/InfinitestCore.java, infinitest-lib/src/main/java/org/infinitest/changedetect/ClassFileFilter.java, infinitest-lib/src/main/java/org/infinitest/changedetect/FileChangeDetector.java, infinitest-lib/src/main/java/org/infinitest/parser/ClassFileIndex.java, infinitest-lib/src/main/java/org/infinitest/parser/ClassFileTestDetector.java, infinitest-lib/src/main/java/org/infinitest/parser/JavaAssistClassParser.java, infinitest-lib/src/main/java/org/infinitest/parser/JavaClassBuilder.java, infinitest-lib/src/main/java/org/infinitest/parser/TestDetector.java, infinitest-lib/src/test/java/org/infinitest/FakeInfinitestCore.java, infinitest-lib/src/test/java/org/infinitest/StubTestDetector.java, infinitest-lib/src/test/java/org/infinitest/WhenTestFileIsRemoved.java, infinitest-lib/src/test/java/org/infinitest/WhenTriggeringACoreUpdate.java, infinitest-lib/src/test/java/org/infinitest/changedetect/WhenLookingForClassFiles.java, infinitest-lib/src/test/java/org/infinitest/parser/ClassFileIndexTest.java, infinitest-lib/src/test/java/org/infinitest/parser/WhenLookingForChangedFiles.java
Biggest performance bottleneck is calling file.lastModified() twice for every file when a change is made, file.isDirectory() is also expensive
- Use java nio's BasicFileAttributes to read the last modified time (see #12)
- Use Files.walk to search the folders
- Monitor for post build events so we run tests once everything is built (see #340)
- Check for removed tests (see #337)
=> Eclipse plugin performance improvements

infinitest-eclipse/src/main/java/org/infinitest/eclipse/workspace/CoreFactory.java, infinitest-intellij/src/main/java/org/infinitest/intellij/plugin/launcher/InfinitestLauncherImpl.java, infinitest-lib/src/main/java/org/infinitest/InfinitestCoreBuilder.java, infinitest-lib/src/test/java/org/infinitest/plugin/WhenConfiguringBuilder.java, infinitest-lib/src/test/java/org/infinitest/plugin/WhenRunningTests.java
we always seem to call setName() after the constructor, so add an argument to the constructor instead so we can add the core name to the error message
see #357
=> fix: set the core name from the constructor instead of a setter

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/IdeaModuleSettings.java
Exclude the SDK modules from the dependencies when building the classpath, fixes #359
=> fix: for gradle projects sdk modules are dependencies

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/IdeaModuleSettings.java, infinitest-intellij/src/test/java/org/infinitest/intellij/IntellijMockBase.java, infinitest-intellij/src/test/java/org/infinitest/intellij/idea/IdeaModuleSettingsTest.java
ClassFileTestDetector.inCurrentProject() checks if the class file path is prefixed by one of the class output dirs, however the path of the class is its canonical path (symbolic converted) while the class output dir is not.
Convert the class output dirs to their canonical paths so we can test if the classes are in these dirs
=> Symlink handling

infinitest-lib/src/main/java/org/infinitest/testrunner/process/NativeConnectionFactory.java
The message is very verbose for the INFO log level, reduce it to CONFIG
=> fix: reduce the log level of the 'starting test runner' message

infinitest-lib/src/main/java/org/infinitest/parser/JavaAssistClass.java, infinitest-lib/src/test/java/com/fakeco/fakeproduct/JUnit5ArchUnitMethodTest.java, infinitest-lib/src/test/java/org/infinitest/parser/JavaAssistClassTest.java
ArchUnit tests can be declared as fields or as methods: also check for methods. Added missing AnalyzeClasses annotation on sample test
=> fix: detect methods annotated with ArchTest as ArchUnit tests

infinitest-intellij/pom.xml
Donwloading all the transitive IntelliJ dependencies takes a very long time on the Github builds, remove some dependencies that we don't seem to need.
The (possibly non exhaustive) list of dependencies we currently need is: 
- execution-impl
- core
- analysis-impl
- editor
- util
- util-ui
- lang
- project-model
- extensions
- java-compiler
- java-psi
- ide
- analysis-impl
=> build: exclude unnecessary intellij dependecies

infinitest-eclipse/src/main/java/org/infinitest/eclipse/SlowTestObserver.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/markers/GenericMarkerRegistry.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/markers/MarkerRegistry.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/markers/ProblemMarkerRegistry.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/markers/SlowMarkerRegistry.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/markers/SlowTestMarkerInfo.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/prefs/PreferenceChangeHandler.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/prefs/PreferencePage.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/prefs/PreferencesConstants.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/WhenMarkingTestsAsSlow.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/WhenWatchingForSlowTests.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/markers/WhenCreatingMarkers.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/prefs/PreferencePageTest.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/prefs/WhenPreferencesAreChanged.java
Added configuration settings for the failed test and slow test markers
Fixes #186
=> feature: configurable severity for Eclipse markers

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/IdeaModuleSettings.java, infinitest-intellij/src/test/java/org/infinitest/intellij/idea/IdeaModuleSettingsTest.java, infinitest-intellij/src/test/java/org/infinitest/intellij/idea/WhenBuildingIdeaModuleClassPath.java
For Gradle projects the resources folders are not included in the classpath, `CompilerModuleExtension` only gets the classes output folders but Gradle puts the resources in `build/resources/test`
For Maven projects the current code includes the test resources of dependent modules while the IntelliJ test runner only includes the test resources of the current module.
Simplifying the code seems to resolve both issues
=> Use `OrderEnumerator` to get the class path elements

infinitest-eclipse/plugin.xml, infinitest-eclipse/src/main/java/org/infinitest/eclipse/InfinitestPlugin.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/prefs/InfinitestPreferenceInitializer.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/prefs/PreferenceChangeHandler.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/prefs/PreferencePage.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/prefs/PreferencesConstants.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/trim/ColorSettings.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/workspace/EclipseWorkspace.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/prefs/InfinitestPreferenceInitializerTest.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/prefs/WhenPreferencesAreChanged.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/trim/WhenShowingStatusInTheStatusBar.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/workspace/WhenCompileErrorsExistInAProject.java, infinitest-lib/src/main/java/org/infinitest/util/InfinitestGlobalSettings.java
When there's a single error in an Eclipse workspace Infinitest stops running tests even if the error might be in an unrelated project.
Added an option to let Infinitest run tests in that case.
Fixes #65
=> feature: added an option to let tests run when projects have errors

infinitest-eclipse/src/main/java/org/infinitest/eclipse/prefs/InfinitestPreferenceInitializer.java, infinitest-lib/src/main/java/org/infinitest/util/InfinitestGlobalSettings.java
The slow test limit is not final and might change, for instance Infinitest's own tests change it so InfinitestPreferenceInitializerTest might fail depending on the order of the test
=> fix: harcode the slow test default limit

infinitest-intellij/src/main/java/org/infinitest/intellij/idea/language/InfinitestHighlightingPassFactory.java, infinitest-intellij/src/main/java/org/infinitest/intellij/idea/window/InfinitestToolWindowFactory.java, infinitest-intellij/src/main/resources/META-INF/plugin.xml, infinitest-intellij/src/test/java/org/infinitest/intellij/IntellijMockBase.java
InfinitestHighlightingPassFactory is declared as a project component and these should be migrated to services. The Jetbrains marketplace flagged that it uses constructor injection and refused the new version of the plugin.
Since we need it to register from somewhere, create it in the InfinitestToolWindowFactory
Fixes #401
=> fix: stop using project components and constructor injection

infinitest-eclipse/src/main/java/org/infinitest/eclipse/InfinitestActivationController.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/event/ClassFileChangeProcessor.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/event/CleanEventProcessor.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/event/CloseProjectEventProcessor.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/event/FilterFileChangeProcessor.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/event/ProjectCleaningEventProcessor.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/event/SaveDetector.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/workspace/ProjectSet.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/WhenActivatingThePlugin.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/event/CloseProjectEventProcessorTest.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/event/WhenNoProcessorsCanHandleEvent.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/event/WhenRespondingToResourceChangeEvents.java, infinitest-lib/src/main/java/org/infinitest/ResultCollector.java, infinitest-lib/src/test/java/org/infinitest/WhenWatchingMultipleCores.java
- The ResultCollector keeps tracks of failed tests and the Eclipse Plugin shows a red bar when there are failure. When a project with failed tests is closed these failures need to be removed or the bar will remain red.
- Listen for PRE_CLOSE events where the resource is a project and close the corresponding core
- These events do not have a delta, so we need the other listeners to check if they can process an event without a delta
Fixes #405
=> fix: listen for events when Eclipse projects are closed

infinitest-eclipse/src/main/java/org/infinitest/eclipse/SlowTestObserver.java, infinitest-eclipse/src/main/java/org/infinitest/eclipse/markers/GenericMarkerRegistry.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/WhenWatchingForSlowTests.java, infinitest-eclipse/src/test/java/org/infinitest/eclipse/markers/WhenCreatingMarkers.java, infinitest-lib/src/test/java/com/fakeco/fakeproduct/DisabledClassJUnit5TestCase.java, infinitest-lib/src/test/java/com/fakeco/fakeproduct/DisabledTestJUnit5TestCase.java, infinitest-lib/src/test/java/com/fakeco/fakeproduct/IgnoredClassJUnit4TestCase.java, infinitest-lib/src/test/java/com/fakeco/fakeproduct/IgnoredTestJUnit4TestCase.java, infinitest-lib/src/test/java/org/infinitest/parser/JavaAssistClassTestDetectionTest.java
Slow test markers are only updated for test that have been executed. In case a test method was removed or disabled we should remove the marker
Fixes #142
=> fix: remove slow test markers for removed/disabled tests

infinitest-intellij/src/main/resources/META-INF/plugin.xml
Unreleased applicationConfigurable needs to be removed since the corresponding class does not exist
Fixes #414
=> fix: remove applicationConfigurable

.github/workflows/build.yml, CONTRIBUTING.md, infinitest-intellij/pom.xml, pom.xml
#431 upgrades to TestNG which requires JDK 11
=> Upgrade from JDK 8 to JDK 11

.github/workflows/build.yml, functional-tests/infinitest-runner-spock-test/pom.xml, infinitest-intellij/src/test/java/org/infinitest/intellij/IntellijMockBase.java, infinitest-lib/src/test/java/org/infinitest/parser/WhenLookingForDependenciesBetweenClasses.java, infinitest-runner-test/pom.xml, infinitest-runner/src/test/java/org/infinitest/testrunner/junit5/JUnit5EventTranslatorTest.java, pom.xml
Upgrade dependencies to make the build compatible with JDK 21:
- Mockito
- JUnit
- Javassist
- Jacoco
- Groovy
- Surefire
Align test libraries versions with Mockito's latest version (since Mockito doesn't support yet the latest JUnit)
=> Add JDK 21 to the matrix build

infinitest-eclipse/src/main/java/org/infinitest/eclipse/markers/ProblemMarkerInfo.java, infinitest-runner/src/main/java/org/infinitest/TestClassInitializationException.java, infinitest-runner/src/main/java/org/infinitest/testrunner/DefaultRunner.java, infinitest-runner/src/main/java/org/infinitest/testrunner/TestEvent.java, infinitest-runner/src/main/java/org/infinitest/testrunner/TestRunnerProcess.java, infinitest-runner/src/test/java/org/infinitest/testrunner/TestRunnerProcessTest.java
Sometimes the test class does not load, for instance when JMockit's agent was not loaded. In that case we want to show the full stacktrace, including the cause(s) exception(s).
This should fix #434
=> Handle the case when the test class failed to initialize
